### ISSUE TITLE
SNS warning topic should only be used by alarms

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-terraform#102]
We have various [SNS topics defined](https://github.com/cds-snc/notification-terraform/blob/main/aws/common/sns.tf). Our main topics are used by alarms, to be notified when a warning or a critical event occurs.

These topics are used also by other components, which are not alarms. Example: the subscription to health events
https://github.com/cds-snc/notification-terraform/blob/bcbf0a715e4690e6da77ef1c9de4c47c728c462c/aws/common/cloudwatch_events.tf#L38

This has been set this way because the SNS topics are already [hooked up to Slack](https://github.com/cds-snc/notification-terraform/blob/main/aws/common/slack.tf) so it was convenient.

**Hooking up non-alarm events to SNS topics related to alarms is not a good practice and will mess up our statistics if we want to count the number of alarms down the road.**

Therefore, we should:
- review all things that use warning and critical SNS topics
- make sure that only alarms use these topics
- create new SNS topics for other events (no need to create one for each, maybe a generic one will do)
- make sure that these new topics are hooked up to Slack at least, consider sending these events to notifications-ops@cds-snc.ca as well

**Comment by dorianjp** [comment]
@AntoineAugusti , I reviewed the TF code and your example is the only non-alarm using the sns topic of either warning or critical.

I did notice we send all RDS events to the SNS warning topic, so a db failover throws to the same SNS topic as db failure. We should discuss whether we want to separate these out for priority.

I can create a new topic and bind it to slack, but do we want a new slack notification binding as well, since we only have two types created, one for warning and one for critical?

**Comment by AntoineAugusti** [comment]
Thanks for taking a look @dorianjp!

I believe there are 2 things to change:
- Cloudwatch health events https://github.com/cds-snc/notification-terraform/blob/bcbf0a715e4690e6da77ef1c9de4c47c728c462c/aws/common/cloudwatch_events.tf#L38
- RDS subscription https://github.com/cds-snc/notification-terraform/blob/3f77ff54f6d42d5225a01a6494d5db59463ee3b6/aws/rds/rds.tf#L67

> I did notice we send all RDS events to the SNS warning topic, so a db failover throws to the same SNS topic as db failure. We should discuss whether we want to separate these out for priority.

I think I'm okay with sending RDS events to the same source for now, only to Slack for now. If we get a DB failure, other critical alarms will trigger and we'll get paged. I want to avoid critical alarms on technical things and prefer critical alarms/pages on business metrics/things that are already broken in production and affecting end users.

I think a single new SNS topic for these 2 is fine and they are health events for AWS services + RDS. You can subscribe an SNS topic to the Slack integration with a code similar to this (here in `us-west-`2, for you it'll be `ca-central-1` so no need to specify a provider)

https://github.com/cds-snc/notification-terraform/blob/3f77ff54f6d42d5225a01a6494d5db59463ee3b6/aws/common/sns.tf#L72-L78
