### ISSUE TITLE
Copy notification-alpha-canada-ca-csv-upload -> notification-canada-ca-production-csv-upload

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-terraform#69]
We need to copy the contents of the `notification-alpha-canada-ca-csv-upload` to `notification-canada-ca-production-csv-upload`.

This worked in testing: https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/

**Comment by AntoineAugusti** [comment]
As been done as part of the migration
