### ISSUE TITLE
Copy notification-alpha-canada-ca-asset-upload -> notification-canada-ca-production-asset-upload

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-terraform#71]
We need to copy the contents of the `notification-alpha-canada-ca-asset-upload` to `notification-canada-ca-production-asset-upload`.

This would ideally be done a couple days before the move.

This worked in testing: https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/

**Comment by AntoineAugusti** [comment]
As been done as part of the migration
