### ISSUE TITLE
Upgrade AWS Terraform to v3

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/notification-terraform#75]
We're not running the latest version of the AWS Terraform provider right now, we should upgrade to use the latest features and bug fixes.

Documentation to upgrade: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade
Relevant file to update the version: https://github.com/cds-snc/notification-terraform/blob/main/env/terragrunt.hcl

I'm not sure we need to change anything, maybe changing the 2 to 3 will do. You should try that in CI, after reading carefully the upgrade guide.

**Comment by jimleroyer** [comment]
Issue: https://github.com/cds-snc/notification-terraform/pull/109

**Comment by AntoineAugusti** [comment]
@jimleroyer You can put `Fixes #issue_number` in your next PRs to automatically close issues
